# Generated by Django 5.2.11 on 2026-02-22 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetition', models.IntegerField(default=0)),
                ('interval', models.IntegerField(default=0)),
                ('easiness_factor', models.FloatField(default=2.5)),
                ('next_review', models.DateField()),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.card')),
            ],
        ),
    ]
