# Generated by Django 5.2.11 on 2026-02-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_telegramlinktoken_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_notification_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
